make run_test
/opt/kontain/bin/km ~/.virtualenvs/litgpt/bin/python3 test.py
15:15:47.306331 sched_setaffinity_hc 1513 vcpu-0  Unsupported
Loading model 'src/checkpoints/stabilityai/stablelm-base-alpha-3b/lit_model.pth' with {'org': 'stabilityai', 'name': 'stablelm-base-alpha-3b', 'block_size': 4096, 'vocab_size': 50254, 'padding_multiple': 512, 'padded_vocab_size': 50688, 'n_layer': 16, 'n_head': 32, 'n_embd': 4096, 'rotary_percentage': 0.25, 'parallel_residual': True, 'bias': True, 'n_query_groups': 32, 'shared_attention_norm': False, '_norm_class': 'LayerNorm', 'norm_eps': 1e-05, '_mlp_class': 'GptNeoxMLP', 'intermediate_size': 16384, 'condense_ratio': 1}
Time to instantiate model: 0.03 seconds.
Traceback (most recent call last):
  File "/home/ubuntu/snapdemos/lit-gpt/test.py", line 9, in <module>
    main()
  File "/home/ubuntu/snapdemos/lit-gpt/test.py", line 5, in main
    base.main(prompt="My name is ",
  File "/home/ubuntu/snapdemos/lit-gpt/src/generate/base.py", line 151, in main
    with lazy_load(checkpoint_path) as checkpoint:
  File "/home/ubuntu/snapdemos/lit-gpt/src/lit_gpt/utils.py", line 223, in __init__
    self.zf = torch._C.PyTorchFileReader(str(fn))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
make: *** [Makefile:21: run_test] Error 1